INSERT INTO roles(name) VALUES('ROLE_STUDENT')
INSERT INTO roles(name) VALUES('ROLE_TEACHER')
INSERT INTO roles(name) VALUES('ROLE_ADMIN')

INSERT INTO courses (description, name, points) VALUES ('Fundamental laws and physics', 'Physics', '4')
INSERT INTO courses (description, name, points) VALUES ('Introduction into natural chemistry', 'Chemistry', '2')
INSERT INTO courses (description, name, points) VALUES ('Beginners course into biology', 'Biology', '2')
INSERT INTO courses (description, name, points) VALUES ('Basic shapes', 'Geometry', '1')
INSERT INTO courses (description, name, points) VALUES ('Ancient History of Humankind', 'History', '6')
INSERT INTO courses (description, name, points) VALUES ('Computer Systems and Design', 'Computer Science', '4')
INSERT INTO courses (description, name, points) VALUES ('Fundamental robotcs course', 'Robotics', '4')
INSERT INTO courses (description, name, points) VALUES ('English language: B2', 'English', '2')
INSERT INTO courses (description, name, points) VALUES ('Great Greek philosophers', 'Philosophy', '2')
INSERT INTO courses (description, name, points) VALUES ('German language: A1', 'German', '1')
INSERT INTO courses (description, name, points) VALUES ('Russian language: B2', 'Russian', '2')
INSERT INTO courses (description, name, points) VALUES ('Analytical and statistical maths', 'Maths', '4')
INSERT INTO courses (description, name, points) VALUES ('Introduction into nuclear physics', 'Nuclear physics', '2')
INSERT INTO courses (description, name, points) VALUES ('Intermediary level Python', 'Python programming', '6')
INSERT INTO courses (description, name, points) VALUES ('The Java programming language', 'Java programming', '4')
INSERT INTO courses (description, name, points) VALUES ('Track and field activies', 'Outdoor sports', '2')
INSERT INTO courses (description, name, points) VALUES ('Overview of software engineering', 'Software engineering', '2')

INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('rob@gmail.com', 'Robbie', 'Smith', '7344645', '1')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('steven@gmail.com', 'Steven', 'Black', '12351235', '2')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('boris@gmail.com', 'Boris', 'Gruber', '612352', '3')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('william@gmail.com', 'William', 'White', '61356123', '4')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('anhony@gmail.com', 'Anthony', 'Kiedis', '12371347', '6')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('tommie@gmail.com', 'Tommie', 'Parkinson', '12351737', '7')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('troy@gmail.com', 'Troy', 'Perkins', '64133443', '8')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('dean@gmail.com', 'Dean', 'Paddon', '71347344', '9')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('johnny@gmail.com', 'Johnny', 'Depp', '2457582', '11')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('brad@gmail.com', 'Brad', 'Pitt', '68257137', '12')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('bob@gmail.com', 'Bob', 'Black', '1451463171', '13')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('george@gmail.com', 'Louise', 'Pool', '8368568', '15')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('amber@gmail.com', 'Amber', 'Heard', '1251235', '10')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('steph@gmail.com', 'Stephanie', 'Gray', '1235665', '14')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('angie@gmail.com', 'Angelina', 'Jolie', '734728616', '5')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('lisa@gmail.com', 'Lisa', 'Perkins', '9568536', '16')
INSERT INTO teachers (email, first_name, last_name, phone_number, course_id) VALUES ('laura@gmail.com', 'Laura', 'Bell', '135757457', '17')

insert into students (first_name, last_name, email, phone_number) values ('Bob', 'Blue', 'bob@gmail.com', '14584989')
insert into students (first_name, last_name, email, phone_number) values ('Will', 'Black', 'will@gmail.com', '694862977')
insert into students (first_name, last_name, email, phone_number) values ('Royce', 'Beggini', 'rbeggini2@about.me', '91281527')
insert into students (first_name, last_name, email, phone_number) values ('Frazier', 'Tinn', 'ftinn0@wisc.edu', '148493989')
insert into students (first_name, last_name, email, phone_number) values ('Rafaello', 'Dodgshun', 'rdohun1@github.com', '69460977')
insert into students (first_name, last_name, email, phone_number) values ('Bobson', 'Dugnutt', 'rbegni2@about.me', '9128241527')
insert into students (first_name, last_name, email, phone_number) values ('Quintilla', 'Pressey', 'qpessey3@etsy.com', '7532715955')
insert into students (first_name, last_name, email, phone_number) values ('Ilene', 'Dowsing', 'idowng4@addthis.com', '6094634107')
insert into students (first_name, last_name, email, phone_number) values ('Livvie', 'Bedinham', 'lbinhm5@businnsider.com', '1528183782')
insert into students (first_name, last_name, email, phone_number) values ('Ramsey', 'Luddy', 'rludy6@cnn.com', '4092999107')
insert into students (first_name, last_name, email, phone_number) values ('Ingra', 'O''Bradden', 'iden7@nhs.uk', '8455708980')
insert into students (first_name, last_name, email, phone_number) values ('Yolande', 'Hunday', 'yhunay8@cmu.edu', '7663863843')
insert into students (first_name, last_name, email, phone_number) values ('Isa', 'Bewshea', 'ibeea9@cafeess.com', '7415230164')
insert into students (first_name, last_name, email, phone_number) values ('Nert', 'Boch', 'nbocha@refece.com', '2355460081')
insert into students (first_name, last_name, email, phone_number) values ('Angil', 'Baigent', 'abagtb@typpad.com', '6504098260')
insert into students (first_name, last_name, email, phone_number) values ('Belia', 'Holton', 'bholtonc@shtfly.com', '1135731871')
insert into students (first_name, last_name, email, phone_number) values ('Reinaldos', 'Pfeffel', 'rpffeld@people.com.cn', '9428819662')
insert into students (first_name, last_name, email, phone_number) values ('Helene', 'Pfaff', 'hpfaffe@huages.com', '2326385674')
insert into students (first_name, last_name, email, phone_number) values ('Selia', 'Peiro', 'speirof@arhnica.com', '2371842488')
insert into students (first_name, last_name, email, phone_number) values ('Larisa', 'Bulleyn', 'lbulyng@sohu.com', '6056748898')
insert into students (first_name, last_name, email, phone_number) values ('Susanne', 'Sleicht', 'sslhth@dailtion.com', '9833500277')
insert into students (first_name, last_name, email, phone_number) values ('Romola', 'Beeton', 'rbeni@google.co.jp', '4313393970')
insert into students (first_name, last_name, email, phone_number) values ('Kelwin', 'Giannoni', 'kganij@ed.gov', '8905806604')

INSERT INTO studcourses (student_id, course_id) VALUES ('1', '1')
INSERT INTO studcourses (student_id, course_id) VALUES ('1', '2')
INSERT INTO studcourses (student_id, course_id) VALUES ('1', '3')
INSERT INTO studcourses (student_id, course_id) VALUES ('2', '5')
INSERT INTO studcourses (student_id, course_id) VALUES ('2', '7')
INSERT INTO studcourses (student_id, course_id) VALUES ('2', '4')
INSERT INTO studcourses (student_id, course_id) VALUES ('3', '8')
INSERT INTO studcourses (student_id, course_id) VALUES ('3', '12')
INSERT INTO studcourses (student_id, course_id) VALUES ('3', '13')
INSERT INTO studcourses (student_id, course_id) VALUES ('4', '13')
INSERT INTO studcourses (student_id, course_id) VALUES ('4', '5')
INSERT INTO studcourses (student_id, course_id) VALUES ('4', '4')
INSERT INTO studcourses (student_id, course_id) VALUES ('5', '1')
INSERT INTO studcourses (student_id, course_id) VALUES ('5', '2')
INSERT INTO studcourses (student_id, course_id) VALUES ('5', '3')
INSERT INTO studcourses (student_id, course_id) VALUES ('6', '6')
INSERT INTO studcourses (student_id, course_id) VALUES ('6', '7')
INSERT INTO studcourses (student_id, course_id) VALUES ('6', '8')
INSERT INTO studcourses (student_id, course_id) VALUES ('6', '9')
INSERT INTO studcourses (student_id, course_id) VALUES ('7', '10')
INSERT INTO studcourses (student_id, course_id) VALUES ('7', '11')
INSERT INTO studcourses (student_id, course_id) VALUES ('7', '12')
INSERT INTO studcourses (student_id, course_id) VALUES ('8', '13')
INSERT INTO studcourses (student_id, course_id) VALUES ('9', '14')
INSERT INTO studcourses (student_id, course_id) VALUES ('9', '15')
INSERT INTO studcourses (student_id, course_id) VALUES ('9', '16')
INSERT INTO studcourses (student_id, course_id) VALUES ('9', '17')
INSERT INTO studcourses (student_id, course_id) VALUES ('9', '13')
INSERT INTO studcourses (student_id, course_id) VALUES ('9', '12')
INSERT INTO studcourses (student_id, course_id) VALUES ('9', '11')
INSERT INTO studcourses (student_id, course_id) VALUES ('9', '10')
INSERT INTO studcourses (student_id, course_id) VALUES ('10', '16')
INSERT INTO studcourses (student_id, course_id) VALUES ('11', '15')
INSERT INTO studcourses (student_id, course_id) VALUES ('12', '14')
INSERT INTO studcourses (student_id, course_id) VALUES ('12', '13')
INSERT INTO studcourses (student_id, course_id) VALUES ('13', '12')
INSERT INTO studcourses (student_id, course_id) VALUES ('14', '11')
INSERT INTO studcourses (student_id, course_id) VALUES ('15', '10')
INSERT INTO studcourses (student_id, course_id) VALUES ('16', '9')
INSERT INTO studcourses (student_id, course_id) VALUES ('17', '8')
INSERT INTO studcourses (student_id, course_id) VALUES ('18', '7')
INSERT INTO studcourses (student_id, course_id) VALUES ('18', '6')

UPDATE courses SET teacher_id = '1' WHERE (course_id = '1')
UPDATE courses SET teacher_id = '2' WHERE (course_id = '2')
UPDATE courses SET teacher_id = '3' WHERE (course_id = '3')
UPDATE courses SET teacher_id = '4' WHERE (course_id = '4')
UPDATE courses SET teacher_id = '5' WHERE (course_id = '5')
UPDATE courses SET teacher_id = '6' WHERE (course_id = '6')
UPDATE courses SET teacher_id = '7' WHERE (course_id = '7')
UPDATE courses SET teacher_id = '8' WHERE (course_id = '8')
UPDATE courses SET teacher_id = '9' WHERE (course_id = '9')
UPDATE courses SET teacher_id = '10' WHERE (course_id = '10')
UPDATE courses SET teacher_id = '11' WHERE (course_id = '11')
UPDATE courses SET teacher_id = '12' WHERE (course_id = '12')
UPDATE courses SET teacher_id = '13' WHERE (course_id = '13')
UPDATE courses SET teacher_id = '14' WHERE (course_id = '14')
UPDATE courses SET teacher_id = '15' WHERE (course_id = '15')
UPDATE courses SET teacher_id = '16' WHERE (course_id = '16')
UPDATE courses SET teacher_id = '17' WHERE (course_id = '17')


INSERT INTO dates (dow, end_time, start_time) VALUES ('0', '09:30:00', '08:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('0', '11:30:00', '10:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('0', '13:30:00', '12:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('0', '14:45:00', '14:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('0', '10:30:00', '08:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('0', '15:30:00', '14:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('1', '09:00:00', '08:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('1', '09:15:00', '08:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('1', '11:15:00', '10:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('1', '12:15:00', '10:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('1', '10:15:00', '08:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('2', '09:30:00', '08:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('2', '11:30:00', '10:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('2', '11:15:00', '09:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('2', '10:15:00', '09:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('3', '12:15:00', '10:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('3', '13:30:00', '12:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('3', '11:45:00', '10:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('4', '15:30:00', '14:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('4', '11:15:00', '09:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('4', '11:30:00', '10:00:00')
INSERT INTO dates (dow, end_time, start_time) VALUES ('4', '11:45:00', '10:00:00')


INSERT INTO events (venue, course_id, date_id) VALUES ('U-512', '1', '1')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-613', '1', '8')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-125', '1', '12')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-612', '1', '19')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-512', '2', '2')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-501', '2', '9')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-129', '2', '14')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-713', '2', '17')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-451', '3', '3')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-111', '3', '7')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-161', '3', '16')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-623', '4', '1')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-753', '4', '3')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-265', '4', '7')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-162', '4', '16')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-428', '5', '4')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-161', '5', '17')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-623', '6', '2')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-753', '6', '13')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-265', '7', '4')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-162', '8', '18')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-428', '9', '11')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-161', '10', '2')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-623', '11', '18')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-753', '12', '18')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-265', '13', '13')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-162', '14', '5')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-428', '15', '11')
INSERT INTO events (venue, course_id, date_id) VALUES ('U-161', '16', '16')

UPDATE students SET profile_pic = 'https://content.fakeface.rest/male_22_098d0b0cd98dcf772476e595ab38b4479943ca80.jpg' WHERE (student_id = '1')
UPDATE students SET profile_pic = 'https://content.fakeface.rest/male_29_fee11f02e3c508249f689125f684307b21c228de.jpg' WHERE (student_id = '2')

UPDATE teachers SET profile_pic = 'https://content.fakeface.rest/male_42_8ad47bcce24893e5120c0b932d68c8ec984749bc.jpg' WHERE (id = '1')
UPDATE teachers SET profile_pic = 'https://content.fakeface.rest/male_37_38c42d74e2413ca6f89f981dbac3e6f83afa45b0.jpg' WHERE (id = '2')


INSERT INTO users (password, username) VALUES ('$2a$10$.AYBxGl440LYL4.HuFycYO7XAUXRaJT7Fj0YHO5z0z0qUnmk4i5xi', 'admin')
INSERT INTO users (password, username) VALUES ('$2a$10$G8wyXmiZ6yvY6tSQaSqq3.lL9zUrLtZGFtkMzvbH085bjyrzM3QnS', 'rob@gmail.com')    --teacher
INSERT INTO users (password, username) VALUES ('$2a$10$G8wyXmiZ6yvY6tSQaSqq3.lL9zUrLtZGFtkMzvbH085bjyrzM3QnS', 'steven@gmail.com') --teacher
INSERT INTO users (password, username) VALUES ('$2a$10$G8wyXmiZ6yvY6tSQaSqq3.lL9zUrLtZGFtkMzvbH085bjyrzM3QnS', 'bob@gmail.com')  --student
INSERT INTO users (password, username) VALUES ('$2a$10$G8wyXmiZ6yvY6tSQaSqq3.lL9zUrLtZGFtkMzvbH085bjyrzM3QnS', 'will@gmail.com') --student

UPDATE teachers SET user_id = '2' WHERE (id = '1')
UPDATE teachers SET user_id = '3' WHERE (id = '2')

UPDATE students SET user_id = '4' WHERE (student_id = '1')
UPDATE students SET user_id = '5' WHERE (student_id = '2')

INSERT INTO user_roles (user_id, role_id) VALUES ('1', '3');
INSERT INTO user_roles (user_id, role_id) VALUES ('2', '2');
INSERT INTO user_roles (user_id, role_id) VALUES ('3', '2');
INSERT INTO user_roles (user_id, role_id) VALUES ('4', '1');
INSERT INTO user_roles (user_id, role_id) VALUES ('5', '1');



