version: '3.9'
services:
    mysql:
        container_name: mysqldb
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        image: 'mysql:8.0.30'
    web-app:
        container_name: backend
        restart: always
        depends_on: 
            - mysql
        ports:
            - '8080:8080'
        image: 'springbootproject:1.0'
        environment:
            - MYSQL_HOST=mysqldb
            - WAIT_HOSTS=mysql:3306
            - WAIT_SLEEP_INTERVAL=5
            - MYSQL_PASSWORD=root
        command: sh -c "/wait && java -jar sbp.jar"
